/**
 * Seed catalog for programmatic SEO pages + sitemaps.
 * Expand this list (or load from Supabase/Turso) toward 10k+ words.
 * Text/IPA is rendered on demand; MP3s are never pre-generated.
 */
export const SEED_WORDS = [
  "epitome",
  "worcestershire",
  "quinoa",
  "anemone",
  "mischievous",
  "hyperbole",
  "albeit",
  "espresso",
  "nuclear",
  "library",
  "colonel",
  "bouquet",
  "chassis",
  "debris",
  "facade",
  "genre",
  "heir",
  "island",
  "jalapeno",
  "knee",
  "liaison",
  "mnemonic",
  "niche",
  "often",
  "pneumonia",
  "queue",
  "rendezvous",
  "subtle",
  "tsunami",
  "victuals",
  "Wednesday",
  "xylophone",
  "yacht",
  "zealous",
  "acai",
  "apple",
  "apricot",
  "avocado",
  "banana",
  "basil",
  "broccoli",
  "bruschetta",
  "cacao",
  "cayenne",
  "chimichurri",
  "chipotle",
  "croissant",
  "culinary",
  "dabble",
  "daiquiri",
  "debut",
  "demure",
  "epitome",
  "espresso",
  "february",
  "foil",
  "forte",
  "gif",
  "gyro",
  "herb",
  "homage",
  "horses",
  "interesting",
  "jewelry",
  "khaki",
  "lasagna",
  "liable",
  "liqueur",
  "macaque",
  "mayonnaise",
  "melange",
  "meringue",
  "mozzarella",
  "nguyen",
  "onion",
  "orchid",
  "oregano",
  "pajamas",
  "paradigm",
  "pheasant",
  "pistachio",
  "poem",
  "potato",
  "pretzel",
  "pronunciation",
  "quinoa",
  "raspberry",
  "recipe",
  "salmon",
  "schedule",
  "sherbet",
  "sioux",
  "squirrel",
  "suite",
  "syringe",
  "tempeh",
  "thyme",
  "tomato",
  "turquoise",
  "vehicle",
  "vignette",
  "worcestershire",
  "zucchini",
  // More high-intent pronunciation lookups (free dictionary / free TTS)
  "asterisk",
  "athlete",
  "cache",
  "caramel",
  "choir",
  "comfortable",
  "coupon",
  "croissant",
  "data",
  "either",
  "envelope",
  "especially",
  "foliage",
  "giraffe",
  "height",
  "hierarchy",
  "ideology",
  "influential",
  "iron",
  "jewelry",
  "length",
  "mayonnaise",
  "mischievous",
  "niche",
  "often",
  "picture",
  "probably",
  "pumpkin",
  "realtor",
  "relevant",
  "remembrance",
  "sherbet",
  "specific",
  "supposedly",
  "temperature",
  "tenet",
  "theater",
  "theatre",
  "triathlon",
  "valuable",
  "vehicle",
  "Wednesday",
  "wherewithal",
  "abbreviate",
  "accessory",
  "acoustic",
  "almond",
  "ancestor",
  "arctic",
  "ask",
  "athlete",
  "barbiturate",
  "candidate",
  "cardamom",
  "congratulations",
  "corroborate",
  "dilate",
  "drowned",
  "escape",
  "espresso",
  "etiquette",
  "existential",
  "extraordinary",
  "facial",
  "february",
  "foliage",
  "formidable",
  "grocery",
  "height",
  "heinous",
  "interpretation",
  "jewelry",
  "legislature",
  "library",
  "masonry",
  "miniature",
  "mischievous",
  "nuclear",
  "orientation",
  "prerogative",
  "prescription",
  "probably",
  "pronunciation",
  "prostate",
  "realtor",
  "relevant",
  "sacrilegious",
  "sherbet",
  "supposedly",
  "triumphant",
  "undoubtedly",
  "veterinary",
  "voluptuous",
  "zoology",
] as const;

export const SITEMAP_CHUNK_SIZE = 1000;

export function uniqueSeedWords(): string[] {
  const seen = new Set<string>();
  const words: string[] = [];
  for (const raw of SEED_WORDS) {
    const word = raw.toLowerCase();
    if (seen.has(word)) continue;
    seen.add(word);
    words.push(word);
  }
  return words.sort();
}

export function sitemapChunkCount(total = uniqueSeedWords().length): number {
  return Math.max(1, Math.ceil(total / SITEMAP_CHUNK_SIZE));
}

export function wordsForSitemapChunk(chunkIndex: number): string[] {
  const all = uniqueSeedWords();
  const start = chunkIndex * SITEMAP_CHUNK_SIZE;
  return all.slice(start, start + SITEMAP_CHUNK_SIZE);
}
