/* Generated by scripts/build-pwa.mjs — do not edit */
"use strict";

var CACHE = "speakur-static-a8740a7710";
var PRECACHE = [
  "/manifest.json",
  "/assets/icon.svg",
  "/assets/404-resolve.js",
  "/assets/critical.css",
  "/assets/global-search-index.json",
  "/assets/global-search-modal.js",
  "/assets/guide-page.js",
  "/assets/guides-data.js",
  "/assets/guides-list.js",
  "/assets/header-search.js",
  "/assets/home.js",
  "/assets/on-demand-word.js",
  "/assets/pwa-install.js",
  "/assets/search-index.js",
  "/assets/site.css",
  "/assets/site.js",
  "/assets/word-index.js",
  "/assets/word-page.css",
  "/assets/word-play.js"
];

self.addEventListener("install", function (event) {
  event.waitUntil(
    caches.open(CACHE).then(function (cache) {
      return cache.addAll(PRECACHE);
    }),
  );
  self.skipWaiting();
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys
          .filter(function (key) {
            return key.indexOf("speakur-static-") === 0 && key !== CACHE;
          })
          .map(function (key) {
            return caches.delete(key);
          }),
      );
    }).then(function () {
      return self.clients.claim();
    }),
  );
});

function isAssetPath(pathname) {
  return pathname.indexOf("/assets/") === 0;
}

function isCacheableAsset(pathname) {
  return /\.(js|css|json|svg|woff2?)$/i.test(pathname);
}

self.addEventListener("fetch", function (event) {
  if (event.request.method !== "GET") return;

  var url;
  try {
    url = new URL(event.request.url);
  } catch {
    return;
  }

  if (url.origin !== self.location.origin) return;

  if (url.pathname === "/manifest.json" || url.pathname === "/sw.js") {
    event.respondWith(
      caches.match(event.request).then(function (cached) {
        return (
          cached ||
          fetch(event.request).then(function (response) {
            var copy = response.clone();
            caches.open(CACHE).then(function (cache) {
              cache.put(event.request, copy);
            });
            return response;
          })
        );
      }),
    );
    return;
  }

  if (isAssetPath(url.pathname) && isCacheableAsset(url.pathname)) {
    event.respondWith(
      caches.match(event.request).then(function (cached) {
        if (cached) return cached;
        return fetch(event.request).then(function (response) {
          if (!response || response.status !== 200) return response;
          var copy = response.clone();
          caches.open(CACHE).then(function (cache) {
            cache.put(event.request, copy);
          });
          return response;
        });
      }),
    );
    return;
  }

  if (event.request.mode === "navigate" || /\.html$/i.test(url.pathname)) {
    event.respondWith(
      fetch(event.request).catch(function () {
        return caches.match("/index.html");
      }),
    );
  }
});
