/**
 * Static sitemap builder.
 * - Collects all public URLs (catalog word pages + hubs + guides + trust pages)
 * - If URLs > 10,000, splits into sitemap-1.xml, sitemap-2.xml, …
 * - Always writes sitemap-index.xml as the master index
 * - Syncs robots.txt → sitemap-index.xml
 *
 * Usage: node scripts/build-sitemap.mjs
 */
import {
  readFileSync,
  writeFileSync,
  readdirSync,
  unlinkSync,
  mkdirSync,
  existsSync,
  copyFileSync,
  renameSync,
} from "fs";
import { join, dirname, basename } from "path";
import { randomBytes } from "crypto";

const ROOT = process.cwd();
const BASE = "https://www.speakur.com";
const CHUNK_SIZE = 10_000;
const OUT_DIR = ROOT;

const catalog = JSON.parse(readFileSync(join(ROOT, "data/catalog.json"), "utf8"));

let guides = [];
try {
  const guideJs = readFileSync(join(ROOT, "assets/guides-data.js"), "utf8");
  guides = JSON.parse(
    guideJs.replace(/^[\s\S]*?window\.SPEAKUR_GUIDES\s*=\s*/, "").replace(/;\s*$/, ""),
  );
} catch {
  guides = [];
}

/** @type {Array<{ path: string, changefreq: string, priority: string }>} */
const entries = [
  { path: "/", changefreq: "daily", priority: "1.0" },
  { path: "/words/", changefreq: "daily", priority: "0.95" },
  { path: "/tools/", changefreq: "weekly", priority: "0.9" },
  { path: "/tools.html", changefreq: "monthly", priority: "0.4" },
  { path: "/tools/ipa/", changefreq: "weekly", priority: "0.85" },
  { path: "/tools/minimal-pairs/", changefreq: "weekly", priority: "0.85" },
  { path: "/tools/homophones/", changefreq: "weekly", priority: "0.8" },
  { path: "/tools/danger-list/", changefreq: "weekly", priority: "0.8" },
  { path: "/tools/us-uk/", changefreq: "weekly", priority: "0.85" },
  { path: "/tools/syllable-stress/", changefreq: "monthly", priority: "0.55" },
  { path: "/tools/name-coach/", changefreq: "monthly", priority: "0.55" },
  { path: "/tools/warm-up/", changefreq: "monthly", priority: "0.55" },
  { path: "/tools/generator/", changefreq: "weekly", priority: "0.75" },
  { path: "/tools/audio/", changefreq: "weekly", priority: "0.7" },
  { path: "/tools/practice/", changefreq: "weekly", priority: "0.7" },
  { path: "/research/", changefreq: "monthly", priority: "0.75" },
  { path: "/guides.html", changefreq: "weekly", priority: "0.85" },
  { path: "/about.html", changefreq: "monthly", priority: "0.7" },
  { path: "/contact.html", changefreq: "monthly", priority: "0.7" },
  { path: "/donate.html", changefreq: "monthly", priority: "0.65" },
  { path: "/privacy.html", changefreq: "monthly", priority: "0.6" },
  { path: "/terms.html", changefreq: "monthly", priority: "0.6" },
  { path: "/build/", changefreq: "weekly", priority: "0.5" },
];

// Trust / policy HTML at site root (Phase 1 pages when present)
const TRUST_HTML = [
  "editorial-policy.html",
  "methodology.html",
  "data-sources.html",
  "correction-policy.html",
  "authors.html",
  "author.html",
  "audio-attribution.html",
  "pronunciation-methodology.html",
];
for (const name of TRUST_HTML) {
  if (existsSync(join(ROOT, name))) {
    entries.push({ path: `/${name}`, changefreq: "monthly", priority: "0.55" });
  }
}

// Auto-discover /tools/*/ and /research/*/ hub pages
function discoverIndexPaths(dirName, priority = "0.8") {
  const base = join(ROOT, dirName);
  if (!existsSync(base)) return;
  for (const ent of readdirSync(base, { withFileTypes: true })) {
    if (!ent.isDirectory()) continue;
    if (existsSync(join(base, ent.name, "index.html"))) {
      entries.push({
        path: `/${dirName}/${ent.name}/`,
        changefreq: "weekly",
        priority,
      });
    }
  }
  if (existsSync(join(base, "index.html"))) {
    entries.push({ path: `/${dirName}/`, changefreq: "weekly", priority: "0.85" });
  }
}
discoverIndexPaths("tools", "0.8");
discoverIndexPaths("research", "0.75");

// IA subsection hubs (generated by scripts/build-ia-hubs.mjs)
try {
  const ia = JSON.parse(readFileSync(join(ROOT, "data/ia-hubs-manifest.json"), "utf8"));
  for (const path of ia.paths || []) {
    if (path === "/words/" || path === "/tools/" || path === "/tools.html" || path === "/research/") continue;
    entries.push({ path, changefreq: "weekly", priority: "0.8" });
  }
} catch {
  // Manifest optional until first ia:hubs run
}

for (const cat of catalog.categories) {
  entries.push({ path: `/${cat.slug}/`, changefreq: "weekly", priority: "0.85" });
  for (const word of cat.words) {
    entries.push({
      path: `/${cat.slug}/${String(word).toLowerCase()}/`,
      changefreq: "monthly",
      priority: "0.8",
    });
  }
}

for (const g of guides) {
  entries.push({
    path: `/guide.html?slug=${encodeURIComponent(g.slug)}`,
    changefreq: "monthly",
    priority: "0.7",
  });
  // Next/App Router guide URLs when deployed alongside static
  entries.push({
    path: `/guides/${encodeURIComponent(g.slug)}`,
    changefreq: "monthly",
    priority: "0.7",
  });
}

// Dedupe by path
const seen = new Set();
const urls = [];
for (const row of entries) {
  if (seen.has(row.path)) continue;
  seen.add(row.path);
  urls.push(row);
}

function escapeXml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function urlsetXml(chunk) {
  const body = chunk
    .map(
      (u) =>
        `  <url><loc>${escapeXml(BASE + u.path)}</loc><changefreq>${u.changefreq}</changefreq><priority>${u.priority}</priority></url>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

function indexXml(files) {
  const lastmod = new Date().toISOString().slice(0, 10);
  const body = files
    .map(
      (file) =>
        `  <sitemap><loc>${escapeXml(`${BASE}/${file}`)}</loc><lastmod>${lastmod}</lastmod></sitemap>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</sitemapindex>\n`;
}

function sleepMs(ms) {
  const sab = new SharedArrayBuffer(4);
  Atomics.wait(new Int32Array(sab), 0, 0, ms);
}

/** Write via unique temp + rename to avoid Windows AV/IDE locks on open files. */
function writeSafe(path, contents, attempts = 20) {
  let lastErr;
  const dir = dirname(path);
  for (let i = 1; i <= attempts; i++) {
    const tmp = join(dir, `.${basename(path)}.${process.pid}.${randomBytes(4).toString("hex")}.tmp`);
    try {
      writeFileSync(tmp, contents);
      try {
        renameSync(tmp, path);
      } catch {
        // Target locked: overwrite in place, then drop temp
        writeFileSync(path, contents);
        try {
          unlinkSync(tmp);
        } catch {
          /* ignore */
        }
      }
      return;
    } catch (err) {
      lastErr = err;
      try {
        unlinkSync(tmp);
      } catch {
        /* ignore */
      }
      sleepMs(Math.min(2000, 200 * i));
    }
  }
  throw lastErr;
}

function copySafe(src, dest, attempts = 20) {
  let lastErr;
  for (let i = 1; i <= attempts; i++) {
    try {
      if (!existsSync(src)) throw Object.assign(new Error(`missing ${src}`), { code: "ENOENT" });
      copyFileSync(src, dest);
      return;
    } catch (err) {
      lastErr = err;
      sleepMs(Math.min(2000, 200 * i));
    }
  }
  throw lastErr;
}

const needsSplit = urls.length > CHUNK_SIZE;
const chunkCount = Math.max(1, Math.ceil(urls.length / CHUNK_SIZE));
const chunkFiles = [];

for (let i = 0; i < chunkCount; i += 1) {
  const slice = urls.slice(i * CHUNK_SIZE, (i + 1) * CHUNK_SIZE);
  const file = `sitemap-${i + 1}.xml`;
  writeSafe(join(OUT_DIR, file), urlsetXml(slice));
  chunkFiles.push(file);
}

// Drop stale higher-number chunks from previous builds
for (const name of readdirSync(OUT_DIR)) {
  const m = /^sitemap-(\d+)\.xml$/.exec(name);
  if (m && Number(m[1]) > chunkCount) {
    try {
      unlinkSync(join(OUT_DIR, name));
    } catch {
      /* ignore lock */
    }
  }
}

const indexBody = indexXml(chunkFiles);
writeSafe(join(OUT_DIR, "sitemap-index.xml"), indexBody);

// Back-compat: sitemap.xml mirrors the index so old Sitemap: lines still work
try {
  writeSafe(join(OUT_DIR, "sitemap.xml"), indexBody);
} catch (err) {
  console.warn(
    `Warning: could not write sitemap.xml (${err.code || err.message}); sitemap-index.xml is authoritative.`,
  );
}

const robots = `# Speakur - https://www.speakur.com
# Allow all crawlers. Sitemaps list every public URL.

User-agent: *
Allow: /

User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: Bingbot
Allow: /

# Primary index (split into sitemap-1.xml ... when over ${CHUNK_SIZE} URLs)
Sitemap: ${BASE}/sitemap-index.xml
# Same index under the classic name
Sitemap: ${BASE}/sitemap.xml
`;

writeSafe(join(OUT_DIR, "robots.txt"), robots);

const publicDir = join(ROOT, "public");
mkdirSync(publicDir, { recursive: true });
copySafe(join(OUT_DIR, "robots.txt"), join(publicDir, "robots.txt"));
copySafe(join(OUT_DIR, "sitemap-index.xml"), join(publicDir, "sitemap-index.xml"));
for (const file of chunkFiles) {
  copySafe(join(OUT_DIR, file), join(publicDir, file));
}
try {
  if (existsSync(join(OUT_DIR, "sitemap.xml"))) {
    copySafe(join(OUT_DIR, "sitemap.xml"), join(publicDir, "sitemap.xml"));
  } else {
    writeSafe(join(publicDir, "sitemap.xml"), indexBody);
  }
} catch (err) {
  console.warn(`Warning: skip public/sitemap.xml (${err.code || err.message})`);
}

console.log(
  `Sitemap build complete: ${urls.length} URLs → ${chunkCount} chunk(s)` +
    (needsSplit ? " (split >10k)" : " (single chunk)") +
    `\n  index: sitemap-index.xml` +
    `\n  files: ${chunkFiles.join(", ")}` +
    `\n  robots: robots.txt + public/robots.txt`,
);

console.log(
  `Sitemap build complete: ${urls.length} URLs → ${chunkCount} chunk(s)` +
    (needsSplit ? " (split >10k)" : " (single chunk)") +
    `\n  index: sitemap-index.xml` +
    `\n  files: ${chunkFiles.join(", ")}` +
    `\n  robots: robots.txt + public/robots.txt`,
);
