/**
 * Generates manifest.json + sw.js for static Speakur deployment and Next public/.
 */
import {
  readFileSync,
  writeFileSync,
  readdirSync,
  statSync,
  mkdirSync,
  copyFileSync,
} from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { createHash } from "crypto";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = join(ROOT, "assets");
const PUBLIC = join(ROOT, "public");

const SITE = {
  name: "Speakur",
  short_name: "Speakur",
  description:
    "Search pronunciations, browse guides, and look up words offline after your first visit.",
  start_url: "/index.html",
  scope: "/",
  display: "standalone",
  orientation: "portrait-primary",
  background_color: "#f6f1e8",
  theme_color: "#0d6e66",
  categories: ["education", "utilities"],
};

/** Core offline tooling — exclude large build artifacts from SW precache */
const REQUIRED_ASSETS = [
  "site.js",
  "pwa-install.js",
  "search-index.js",
  "header-search.js",
  "word-lookup.js",
  "on-demand-word.js",
  "word-play.js",
  "home.js",
  "guide-page.js",
  "guides-list.js",
  "404-resolve.js",
  "site.css",
  "word-page.css",
  "icon.svg",
];

/** Never precache — too large or build-only */
const PRECACHE_SKIP = new Set([
  "word-index.js",
  "word-paths.json",
  "word-paths.json.gz",
  "global-search-index.json",
  "guides-data.js",
  "speakur-favicon-source.png",
]);

function listAssetFiles() {
  const found = new Set(REQUIRED_ASSETS);
  try {
    for (const name of readdirSync(ASSETS)) {
      const p = join(ASSETS, name);
      if (!statSync(p).isFile()) continue;
      if (/\.(js|css|json|svg|woff2?)$/i.test(name)) found.add(name);
    }
  } catch {
    /* assets dir missing */
  }
  return [...found].sort();
}

function buildPrecacheUrls(files) {
  const urls = ["/manifest.json", "/assets/icon.svg"];
  for (const file of files) {
    if (file === "icon.svg") continue;
    if (PRECACHE_SKIP.has(file)) continue;
    if (/^ad-config\.js$/i.test(file)) continue;
    urls.push(`/assets/${file}`);
  }
  return urls;
}

function cacheVersion(urls) {
  return createHash("sha1").update(urls.join("|")).digest("hex").slice(0, 10);
}

function buildManifest() {
  return {
    ...SITE,
    icons: [
      {
        src: "/assets/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        src: "/assets/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/assets/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any maskable",
      },
    ],
  };
}

function buildServiceWorker(precacheUrls, version) {
  const cacheName = `speakur-static-${version}`;
  return `/* Generated by scripts/build-pwa.mjs — do not edit */
"use strict";

var CACHE = ${JSON.stringify(cacheName)};
var PRECACHE = ${JSON.stringify(precacheUrls, null, 2)};

self.addEventListener("install", function (event) {
  event.waitUntil(
    caches.open(CACHE).then(function (cache) {
      return cache.addAll(PRECACHE);
    }),
  );
  self.skipWaiting();
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys
          .filter(function (key) {
            return key.indexOf("speakur-static-") === 0 && key !== CACHE;
          })
          .map(function (key) {
            return caches.delete(key);
          }),
      );
    }).then(function () {
      return self.clients.claim();
    }),
  );
});

function isAssetPath(pathname) {
  return pathname.indexOf("/assets/") === 0;
}

function isCacheableAsset(pathname) {
  return /\\.(js|css|json|svg|woff2?)$/i.test(pathname);
}

self.addEventListener("fetch", function (event) {
  if (event.request.method !== "GET") return;

  var url;
  try {
    url = new URL(event.request.url);
  } catch {
    return;
  }

  if (url.origin !== self.location.origin) return;

  if (url.pathname === "/manifest.json" || url.pathname === "/sw.js") {
    event.respondWith(
      caches.match(event.request).then(function (cached) {
        return (
          cached ||
          fetch(event.request).then(function (response) {
            var copy = response.clone();
            caches.open(CACHE).then(function (cache) {
              cache.put(event.request, copy);
            });
            return response;
          })
        );
      }),
    );
    return;
  }

  if (isAssetPath(url.pathname) && isCacheableAsset(url.pathname)) {
    event.respondWith(
      caches.match(event.request).then(function (cached) {
        if (cached) return cached;
        return fetch(event.request).then(function (response) {
          if (!response || response.status !== 200) return response;
          var copy = response.clone();
          caches.open(CACHE).then(function (cache) {
            cache.put(event.request, copy);
          });
          return response;
        });
      }),
    );
    return;
  }

  if (event.request.mode === "navigate" || /\\.html$/i.test(url.pathname)) {
    event.respondWith(
      fetch(event.request).catch(function () {
        return caches.match("/index.html");
      }),
    );
  }
});
`;
}

function writeOutputs(manifest, swSource) {
  const manifestJson = JSON.stringify(manifest, null, 2);

  writeFileSync(join(ROOT, "manifest.json"), manifestJson);
  writeFileSync(join(ROOT, "sw.js"), swSource);

  mkdirSync(PUBLIC, { recursive: true });
  mkdirSync(join(PUBLIC, "assets"), { recursive: true });
  writeFileSync(join(PUBLIC, "manifest.json"), manifestJson);
  writeFileSync(join(PUBLIC, "sw.js"), swSource);
  copyFileSync(join(ASSETS, "pwa-install.js"), join(PUBLIC, "pwa-install.js"));
  try {
    copyFileSync(join(ASSETS, "icon.svg"), join(PUBLIC, "assets", "icon.svg"));
  } catch {
    /* optional */
  }
}

const assetFiles = listAssetFiles();
const precache = buildPrecacheUrls(assetFiles);
const version = cacheVersion(precache);
const manifest = buildManifest();
const sw = buildServiceWorker(precache, version);

writeOutputs(manifest, sw);

console.log(
  `PWA build: manifest.json + sw.js (${precache.length} precache URLs, cache speakur-static-${version})`,
);
